// Transcrição resumida das composições informadas a partir das atas.
// A ausência de um nome/cargo indica que o registro consultado não o confirmou.
export const boards: {year:string;note?:string;members:string[]}[] = [
  {year:'2006 · Missão Batista',members:['Presidente e pastor: Pr. Alexandre Costa de Moraes','Vice-moderador: Orli Perilio dos Anjos','Secretaria: Edinilda Badaró e Maria Perilio Siqueira Floriano']},
  {year:'2007 · Missão Batista',note:'Não há composição anual completa nesse conjunto de atas.',members:['Artur Cardoso Filho presidiu reuniões como moderador/vice-moderador; posteriormente, Pr. Eliseu Maria passou a presidi-las.']},
  {year:'2008 · Missão Batista',members:['1º presidente: Artur Cardoso Filho','2º vice-presidente: Leomar João da Silva','1ª secretária: Maria Perilio Siqueira Floriano','2ª secretária: Maria Aparecida Tomáz de Souza','1º tesoureiro: Orli Perilio dos Anjos','2º tesoureiro: Sidiney Guimarães']},
  {year:'2009',note:'As atas já usam o nome Primeira Igreja Batista em Brejetuba, mas a eleição anual completa não foi localizada.',members:[]},
  {year:'2010',members:['Presidente: Pr. Eliseu Maria','1º vice-presidente: Artur Cardoso Filho','2º vice-presidente: Jadir Luiz da Silva','1ª secretária: Maria Perilio Siqueira Floriano','2ª secretária: Karina Perilio Siqueira Martins','1º tesoureiro: Jadir Luiz da Silva','2º tesoureiro: Orli Perilio dos Anjos']},
  {year:'2011',note:'Maria Perilio aparece nos dois cargos indicados, conforme o registro.',members:['Presidente: Pr. Eliseu Maria','1º vice-presidente: Artur Cardoso Filho','2ª vice-presidente e 1ª secretária: Maria Perilio Siqueira Floriano','2º secretário: Jefferson Martinuzzo','1º tesoureiro: Jadir Luiz da Silva','2º tesoureiro: Orli Perilio dos Anjos']},
  {year:'2012',members:['Presidente: Pr. Eliseu Maria','1º vice-presidente: Artur Cardoso Filho','2º vice-presidente: Jefferson Martinuzzo','1ª secretária: Maria Perilio Siqueira Floriano','2ª secretária: Giselle Teodoro Teixeira','1º tesoureiro: Jadir Luiz da Silva','2º tesoureiro: Orli Perilio dos Anjos']},
  {year:'2013',note:'A eleição não nomeia presidente nessa relação. Em janeiro, as reuniões já eram presididas pelo Pr. Thiago Machado de Mello.',members:['1º vice-presidente: Artur Cardoso Filho','2ª vice-presidente: Adriana Aparecida de Miranda Guimarães','1ª secretária: Maria Perilio Siqueira Floriano','2ª secretária: Giselle Teodoro Teixeira Cardoso','1º tesoureiro: Orli Perilio dos Anjos','2º tesoureiro: Jadir Luiz da Silva']},
  {year:'2014',note:'A eleição consultada não nomeia presidente.',members:['1º vice-presidente: Artur Cardoso Filho','2ª vice-presidente: Adriana Aparecida de Miranda Guimarães','1º secretário: Jefferson Martinuzzo','2ª secretária: Maria Perilio Siqueira Floriano','1º tesoureiro: Orli Perilio dos Anjos','2º tesoureiro: Jadir Luiz da Silva']},
  {year:'2015',note:'O Pr. Abner Well’Antonio tomou posse em 25 de abril de 2015.',members:['1º vice-presidente: Artur Cardoso Filho','2º vice-presidente: Jadir Luiz da Silva','1º secretário: Jefferson Martinuzzo','2ª secretária: Maria Perilio Siqueira Floriano','1º tesoureiro: Orli Perilio dos Anjos','2º tesoureiro: Jadir Luiz da Silva']},
  {year:'2016',members:['Presidente: Pr. Abner Well’Antonio','1º vice-presidente: Zilone Siqueira Pereira','2º vice-presidente: Jadir Luiz da Silva','1ª secretária: Maria Perilio Siqueira Floriano','2º secretário: Jefferson Martinuzzo','1º tesoureiro: Orli Perilio dos Anjos','2º tesoureiro: Jadir Luiz da Silva']},
  {year:'2017',note:'Eleição presidida pelo Pr. Natanael Zuccon. A indicação de outro 2º tesoureiro na transcrição requer conferência no original. Pr. Geraldo Antônio Mielki tomou posse em 11 de fevereiro.',members:['1ª vice-presidente: Rosa Maria Siqueira Perilio','2º vice-presidente: Jadir Luiz da Silva','1ª secretária: Maria Perilio Siqueira Floriano','1º tesoureiro: Orli Perilio dos Anjos','2ª tesoureira: Maria Rosa de Oliveira Lecontino']},
  {year:'2018',note:'Há duas composições diferentes nos registros consultados. Ambas aparecem aqui como transcrições provisórias; os cargos dependem de conferência na ata original.',members:['Registro A: Jadir Luiz da Silva (1º vice), Heliomar Dias Pilon (2º vice), Maria Perilio Siqueira Floriano (1ª secretária), Karina Perilio Siqueira Martins (2ª secretária), Orli Perilio dos Anjos (1º tesoureiro) e Maria Rosa de Oliveira Lecontino (2ª tesoureira).','Registro B: Pr. Geraldo Antônio Mielki (presidente), Jucélio dos Santos Virgínio (1º vice), Rosa Maria Siqueira Perilio (2ª vice), Maria Perilio Siqueira Floriano (1ª secretária), Olinda Maria Gonçalves (2ª secretária), Orli Perilio dos Anjos (1º tesoureiro) e Jadir Luiz da Silva (2º tesoureiro).']},
  {year:'2019',members:['Presidente: Pr. Geraldo Antônio Mielki','1º vice-presidente: Jucélio dos Santos Virgínio','2ª vice-presidente: Rosa Maria Siqueira Perilio','1ª secretária: Maria Perilio Siqueira Floriano','2ª secretária: Olinda Maria Gonçalves','1º tesoureiro: Orli Perilio dos Anjos','2º tesoureiro: Heliomar Dias Pilon']},
  {year:'2020',members:['Presidente: Pr. Geraldo Antônio Mielki','1º vice-presidente: Jucélio dos Santos Virgínio','2º vice-presidente: Danilton Siqueira Corrêa','1ª secretária: Olinda Maria Gonçalves','2ª secretária: Andreia Souza Pinheiro','1º tesoureiro: Orli Perilio dos Anjos','2ª tesoureira: Ester Rodrigues Gonçalves']},
  {year:'2021 · sem pastor titular',members:['Presidente: Adriana Aparecida de Miranda Guimarães','1º vice-presidente: Danilton Siqueira Corrêa','2ª vice-presidente: Karina Perilio Siqueira Martins','1ª secretária: Maria Perilio Siqueira Floriano','2ª secretária: Andreia Souza Pinheiro','1º tesoureiro: Orli Perilio dos Anjos','2º tesoureiro: Jadir Luiz da Silva']},
  {year:'2022 · sem pastor titular',members:['Presidente: Adriana Aparecida de Miranda Guimarães','1º vice-presidente: Danilton Siqueira Corrêa','2ª vice-presidente: Andreia Souza Pinheiro','1ª secretária: Maria Perilio Siqueira Floriano','2ª secretária: Maria Aparecida dos Santos Nunes','1º tesoureiro: Aguimar de Paula Nunes','2º tesoureiro: Orli Perilio dos Anjos']},
  {year:'2023 · antes de 24 de junho',note:'A eleição não preencheu a presidência. Em 24 de junho de 2023, Pr. Márcio Pereira de Souza tomou posse como pastor e presidente.',members:['1ª vice-presidente: Adriana Aparecida de Miranda Guimarães','2º vice-presidente: Danilton Siqueira Corrêa','1ª secretária: Millena Perilio Viana Lourenço','2ª secretária: Maria Perilio Siqueira Floriano','1º tesoureiro: Orli Perilio dos Anjos','2º tesoureiro: Jadir Luiz da Silva']},
  {year:'2024',members:['Presidente: Pr. Márcio Pereira de Souza','1º vice-presidente: Danilton Siqueira Correia','2º vice-presidente: Paulo Floriano','1ª secretária: Maria Perilio Siqueira Floriano','2ª secretária: Millena Perilio Viana Lourenço','1º tesoureiro: Aguimar de Paula Nunes','2º tesoureiro: Jadir Luiz da Silva']},
];
